MTES-MCT/stop-punaises

src/Controller/EntrepriseViewController.php
src/Controller/Security/AccountActivationController.php
src/Controller/Security/ResetPasswordController.php
src/Entity/Entreprise.php
src/Entity/User.php
src/Event/EntrepriseUpdatedEvent.php
src/EventSubscriber/EntrepriseUpdatedSubscriber.php
src/Exception/User/RequestPasswordNotAllowedException.php
src/Factory/UserFactory.php
src/Form/EntrepriseType.php
src/Manager/UserManager.php
src/Security/AppAuthenticator.php
templates/entreprise_view/index.html.twig

* Affichage email user sur les écran entreprise (view, edit)
* Modification email user si mise à jour email entreprise
* Vérifie si user peut mettre à jour son mot de passe
* Ajout message erreur si token invalide ou expiré
* Vérifie si l'utilisateur peut se connecter (statut actif)

Sécurité et gestion des emails entreprise

---

src/Command/AddUserCommand.php
src/Entity/User.php

```
php bin/console app:add-user toto@yopmail.com
```

Ajout commande création utilisateur

---

templates/front/index.html.twig

Fix for https://github.com/MTES-MCT/histologe/issues/639 and https://github.com/MTES-MCT/histologe/issues/638

fix homepage design

---

assets/styles/app.scss
templates/front/information.html.twig

Fix for https://github.com/MTES-MCT/histologe/issues/643 and https://github.com/MTES-MCT/histologe/issues/642 and https://github.com/MTES-MCT/histologe/issues/640

information page design

---

migrations/Version20221019104326.php
phpunit.xml.dist
src/Controller/EntrepriseViewController.php
src/Entity/Employe.php
src/Entity/Entreprise.php
src/Form/EmployeType.php
src/Form/EntrepriseType.php
src/Manager/EmployeManager.php
src/Twig/AppExtension.php
templates/entreprise_view/index.html.twig
templates/entreprise_view/not-found.html.twig
tests/SmokeTest.php

```
make load-migrations
```
* https://github.com/MTES-MCT/histologe/issues/661

Ajout contrainte téléphone + refacto

---

composer.json
composer.lock
migrations/Version20221020132704.php
src/Controller/SignalementCreateController.php
src/DataFixtures/Loader/LoadSignalementData.php
src/Entity/Enum/InfestationLevel.php
src/Entity/Signalement.php
src/Form/SignalementType.php
src/Service/Signalement/ReferenceGenerator.php
src/Twig/NiveauInfestation.php
templates/common/components/niveau-infestation.html.twig
templates/signalement_create/index.html.twig
templates/signalement_create/tab-2.html.twig
templates/signalement_view/tab-intervention.html.twig

```
make composer
make load-migrations
```
* https://github.com/MTES-MCT/histologe/issues/663
* https://github.com/MTES-MCT/histologe/issues/668
* https://github.com/MTES-MCT/histologe/issues/656

Retour formulaire signalement

---

.env
.env.sample
src/Twig/AppExtension.php

[Dev] MAJ du port  smtp mailcatcher

---

templates/front/index.html.twig

Mise à jour contenu homepage

---

assets/styles/app.scss

https://github.com/MTES-MCT/stop-punaises/issues/92

change icon over search address input field

---

assets/controllers/form_signalement_front.js
migrations/Version20221122170839.php
src/Entity/Signalement.php
src/Form/SignalementFrontType.php
templates/front_signalement/_partial_step_info_locataire.html.twig
templates/front_signalement/index.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/81

add new locataire fields to signalements

---

templates/base-back.html.twig
templates/dashboard/index.html.twig
templates/dashboard/nav.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/85

review dashboard menu

---

assets/controllers/form_signalement_front.js

https://github.com/MTES-MCT/stop-punaises/issues/105

confirmation page for signalement hors territoire

---

assets/controllers/form_signalement_front.js
templates/common/footer.html.twig
templates/front/information.html.twig
templates/front_signalement/_partial_step_recommandation.html.twig
templates/signalement_view/tab-intervention.html.twig
templates/signalement_view/tab-logement.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/93

change message when niveau infestation equals 0

---

config/packages/twig.yaml
templates/base-back.html.twig
templates/base.html.twig
templates/common/analytics.html.twig

Matomo - Ajout code tracking

---

assets/app.js
assets/controllers/form_send_message.js
assets/styles/app.scss
migrations/Version20221208181142.php
src/Controller/SignalementMessageController.php
src/Dto/MessageResponse.php
src/Entity/Entreprise.php
src/Entity/Message.php
src/EventSubscriber/MessageAddedSubscriber.php
src/Factory/MessageFactory.php
src/Manager/MessageManager.php
src/Service/Mailer/MailerProvider.php
templates/base-back.html.twig
templates/common/components/signalement-detail.html.twig
templates/signalement_view/tab-messages.html.twig
templates/signalement_view/tab-signalement.html.twig

[BO] Envoi de message à l'usager

---

assets/controllers/form_send_message.js
assets/styles/app.scss
migrations/Version20221213042808.php
src/Controller/Front/SignalementController.php
src/Controller/Front/SuiviUsagerViewController.php
src/Controller/SignalementMessageController.php
src/Controller/SignalementViewController.php
src/Entity/Entreprise.php
src/Entity/Event.php
src/Entity/Message.php
src/Entity/MessageThread.php
src/Entity/Signalement.php
src/Event/MessageAddedEvent.php
src/EventSubscriber/MessageAddedSubscriber.php
src/Factory/EventFactory.php
src/Factory/MessageFactory.php
src/Factory/MessageThreadFactory.php
src/Manager/EventManager.php
src/Manager/MessageManager.php
src/Manager/MessageThreadManager.php
src/Repository/EventRepository.php
src/Repository/MessageThreadRepository.php
src/Service/Mailer/MailerProvider.php
templates/common/components/messages-thread.html.twig
templates/common/components/signalement-detail-evenements.html.twig
templates/front_suivi_usager/messages_thread.html.twig
templates/front_suivi_usager/modal-probleme-resolu-pro.html.twig
templates/signalement_view/tab-messages.html.twig

[FO] Envoi message depuis page de suivi

---

src/Manager/EntrepriseManager.php

https://github.com/MTES-MCT/stop-punaises/issues/160

entreprise manager with good entity name

---

src/Controller/SignalementViewController.php
templates/front_suivi_usager/modal-choice-estimation.html.twig
templates/signalement_view/modal-send-estimation.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/124

error message when empty estimation sent

---

templates/common/footer.html.twig
templates/common/header-back.html.twig
templates/common/header.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/175

fix header minister name

---

assets/styles/app.scss
templates/signalement_view/signalement.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/158

fix columns in signalement view

---

assets/styles/app.scss
templates/dashboard/nav.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/156

add shadow to dashboard menu

---

assets/controllers/form_signalement_front.js
templates/front_signalement/_partial_step_info_logement.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/163

add error on signalement address field

---

assets/controllers/list_signalement.js
templates/signalement_list/signalements.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/155

fix filter signalements on territory

---

assets/controllers/form_signalement_front.js

https://github.com/MTES-MCT/stop-punaises/issues/154

email when territory is not open

---

assets/controllers/list_signalement.js

https://github.com/MTES-MCT/stop-punaises/issues/159

fix filters for signalements on closed territories

---

src/Controller/Front/SuiviUsagerViewController.php
src/Controller/SignalementViewController.php
src/EventSubscriber/MessageAddedSubscriber.php
src/Manager/AbstractManager.php
src/Manager/EventManager.php
src/Manager/MessageManager.php
src/Manager/MessageThreadManager.php
src/Repository/EventRepository.php
templates/common/components/signalement-detail-evenements.html.twig
templates/front_suivi_usager/messages_thread.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/123#issuecomment-1352391163

Afficher les événements message pour les entreprise et administrateurs

---

src/Controller/SignalementViewController.php
src/Entity/Intervention.php
templates/signalement_view/modal-refuse-signalement.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/120 and https://github.com/MTES-MCT/stop-punaises/issues/164

control on commentaire when estimation refused

---

templates/dashboard/nav.html.twig

https://github.com/MTES-MCT/stop-punaises/issues/157

add focus on dashboard menu when in subitems

---

src/Controller/SignalementViewController.php

[BO - Signalement] Impossible d'accéder aux signalements si Admin

---

assets/controllers/form_send_message.js
src/EventSubscriber/MessageAddedSubscriber.php

Correctifs (ticket en description)

---

.env
.env.sample
templates/signalement_view/signalement.html.twig

[BO - Signalement] Masquer le bouton "marquer comme traiter" si pas d'estimation acceptée

---

src/Service/Mailer/MailerProvider.php

[Email - Auto traitement - Problème résolu] Mauvais lien

---

migrations/Version20230103103501.php
src/Controller/Front/SignalementController.php
src/Controller/Front/SuiviUsagerViewController.php
src/Controller/SignalementResolveController.php
src/Entity/Signalement.php
src/Service/Mailer/MailerProvider.php
src/Service/Signalement/EventsProvider.php
templates/front_suivi_usager/messages_thread.html.twig

Linked to: https://github.com/MTES-MCT/stop-punaises/issues/144
Need to make _load-migrations_
Add a public uuid to signalements for usagers.

add public uuid for suivi of signalement

---

.github/workflows/main.yml
composer.json
composer.lock
config/bundles.php
config/packages/sentry.yaml
config/packages/test/dama_doctrine_test_bundle.yaml
phpunit.xml.dist
symfony.lock

Lié à #238 
https://sentry.incubateur.net/share/issue/6e9451051b3d404082774ea42a452d19/

Sentry + Ajout tache test dans la CI

---

src/Repository/SignalementRepository.php

Link to https://github.com/MTES-MCT/stop-punaises/issues/242

fix count on dashboard admin

---

Makefile

Add a npm build on "make build" command to prevent an exception on local. Is it a good idea ?

Fix makefile to add a npm build to build commant

---

src/Controller/Front/HomeController.php
templates/common/footer.html.twig
templates/front/mentions-legales.html.twig

Ajout des mentions légales : https://github.com/MTES-MCT/stop-punaises/issues/251

add mentions legales

---

templates/front/information.html.twig

Lié à https://github.com/MTES-MCT/stop-punaises/issues/239

update information text

---

templates/front/information.html.twig

Lié à https://github.com/MTES-MCT/stop-punaises/issues/246

add pictures on info page when responsive

---

src/Controller/Front/SuiviUsagerViewController.php
src/Manager/EventManager.php
src/Repository/EventRepository.php

Lié à https://github.com/MTES-MCT/stop-punaises/issues/260

fix deactivation of previous event

---

templates/front/index.html.twig
templates/front_suivi_usager/index.html.twig
templates/signalement_view/signalement.html.twig

Pour les tickets 
- https://github.com/MTES-MCT/stop-punaises/issues/273
- https://github.com/MTES-MCT/stop-punaises/issues/275
- https://github.com/MTES-MCT/stop-punaises/issues/276

Modifications de contenu

---

src/Twig/AppExtension.php
templates/signalement_list/historique.html.twig
templates/signalement_list/hors-perimetre.html.twig
templates/signalement_list/signalements.html.twig

Correction du tri dans les tableaux de listes du back-office

---

docker-compose.yml
src/Exception/User/UserAccountAlreadyActiveException.php

Modification du message lors de l'activation de compte déjà actif et auto-login de phpmyadmin

---

assets/controllers/form_signalement_front.js
templates/dashboard/index.html.twig

Mise à jour de la règle de calcul du niveau d'infestation

---

assets/controllers/form_signalement_front.js

Correction de première étape de saisie de signalement

Correction de première étape de saisie de signalement

---

src/DataFixtures/Files/Territoire.yml

Modification des fixtures pour que seul le 13 soit un territoire actif

Modification des fixtures pour que seul le 13 soit un territoire actif

---

templates/signalement_view/signalement.html.twig

#308    
Changement de texte de bouton

change button label for entreprise closure

---

src/Entity/Employe.php
src/Entity/Entreprise.php
src/Entity/Signalement.php
src/Form/EmployeType.php
src/Form/EntrepriseType.php

#314    
Acceptation des numéros de téléphones commençant par 08
* Modification des expressions régulières de validation des numéro de téléphones

[Formulaires] Acceptation des numéros de téléphones commençant par 08

---

assets/app.js
assets/controllers/weekly_slider.js
package-lock.json
package.json
public/js/maps.js
src/Controller/CartographieController.php
templates/base-back.html.twig
templates/base.html.twig
templates/cartographie/curseur.html.twig
templates/cartographie/index.html.twig
webpack.config.js

#320    
Ajoute un slider jquery où chaque cran est une semaine
Branche la date générée par le slider au controller de la carto
* Création d'un controller js weekly_slider
* Envoi du formulaire au controller lors de l'appel à getMarkers

[BO - Carto] Ajouter un slider temporel sur la nouvelle carto

---

assets/app.js
assets/controllers/weekly_slider.js
assets/styles/app.scss
package-lock.json
package.json
public/js/maps.js
src/Command/GeolocateCommand.php
src/Controller/CartographieController.php
src/DataFixtures/Files/Signalement.yml
src/DataFixtures/Loader/LoadSignalementData.php
src/Repository/SignalementRepository.php
src/Service/Signalement/CartoStatutCalculator.php
src/Service/Signalement/CartoStatutService.php
templates/base-back.html.twig
templates/base.html.twig
templates/cartographie/curseur.html.twig
templates/cartographie/index.html.twig
webpack.config.js

#320    
Remplacement de la carte iFrame par une carte de chaleur.
Les signalements résolus ne sont pas affichés.
Les signalements peuvent être affichés avec 2 intensités différentes : 
- état "trace" si le signalement est clos depuis moins de 4 mois, mais par encore résolu, ou si le signalement est vieux de moins dde 4 mois et hors territoire d'expérimentation
- état "en cours" : si le signalement n'est pas clos,
* Ajout d'un fichier maps.js avec l'affichage des différens signalements
* Ajout d'une fonction findAllWithGeoData() dans le signalementRepository
* Ajout d'un CartoStatutService qui définit le statut des signalements en fonction des critères définis ci-dessus et qui seront amenés à évoluer
* Modification des fixtures pour avoir des adresses différentes avec leur geolocalisation …

[BO - Cartographie] Remplacer la carte actuelle en iFrame par une carte de chaleur

---

scripts/upload-s3.sh
src/Command/GeolocateCommand.php
src/Command/ImportSignalementCommand.php
src/Entity/Behaviour/TimestampableTrait.php
src/Entity/Signalement.php
src/Factory/SignalementFactory.php
src/Manager/AbstractManager.php
src/Manager/SignalementManager.php
src/Service/Import/CsvParser.php
src/Service/Import/CsvWriter.php
src/Service/Import/Signalement/SignalementImportLoader.php
src/Service/Import/Signalement/SignalementImportMapper.php
src/Service/Signalement/GeolocateService.php
src/Service/Upload/UploadHandlerService.php

#325   
Création d'une commande qui permet d'importer les signalements historiques d'une entreprise, en fonction de son uuid.
cf doc ici https://github.com/MTES-MCT/stop-punaises/wiki/Import-signalements-historiques
* Rajout du script d'upload (récupéré sur histologe)
* création de la commande import-signalement
* création de la signalementFactory
* création des services d'import csvparser et csvwriter (récupérés sur histologe)
* Création d'un geolocateService
* Création d'un signalementImportLoader et SignalementImportMapper (même principe qu'histologe)
- 645ba1e3ccc7a 	EPUR
- 645ba4262be42 	CANEM DETECT
- 63b6c306ec8bc 	Antipesti 
- 63b6c1f37473d 	A3DS
- 63b6c29ebf3a9 	A4D Sanitation
- 645ba3835a509 	COTIERE HYGIENE ASSAINISSEMENT
- 63b6c22f88ef0 	DKM Experts
- 63bd8aa4bdf8d 	Eco flair …

[BO - Signalements] Créer une commande d'import de signalements historiques

---

src/Command/ImportSignalementCommand.php
src/DataFixtures/Loader/LoadSignalementData.php
src/Repository/SignalementRepository.php
src/Service/Import/Signalement/SignalementImportLoader.php
src/Service/Signalement/ReferenceGenerator.php

#325    
cf https://github.com/MTES-MCT/stop-punaises/pull/327

[BO - Import Signalement] Récupère hotfix sur develop

---

.env
.env.sample
config/services.yaml

#334    
Envoyer les messages de formulaire de contact vers la boite contact@stop-punaises.beta.....
* Ajout d'une nouvelle variable d'environnement

[FO - Contact] Mettre à jour l'adresse de destination

---

src/Form/SignalementType.php

#338    
Correction index de tableau dans les coordonnées de signalement
- [] Créer un signalement et vérifier que les coordonnées géographiques s'enregistrent correctement

[QA] Correction index de tableau

---

.github/pull_request_template.md
src/Twig/AppExtension.php

#317    
Correction de paramètre nul pour le format du téléphone

[QA] Correction de paramètre nul pour le format du téléphone

---

src/Controller/Front/SignalementController.php

#401    
Lors de l'ajout d'un signalement, on vérifie si on a de la géoloc, sinon on rappelle le GeolocateService
* Appel au GeolocateService dans `app_front_signalement_add`

[QA] ajoute la geolocalisation sur les signalements dans les territoires non ouverts

---

assets/controllers/form_signalement_front.js
assets/styles/app.scss
src/Entity/Signalement.php
src/Form/SignalementFrontType.php
templates/front_signalement/_partial_step_info_logement.html.twig

#351    
Prise en charge de la gestion de la superficie en int
* Correction de l'entité et du formType
* Modification js pour informer l'usager

[QA] Problème conversion superficie

---

scripts/postdeploy.sh

#372    
Description de la modification apportée
* Liste des changements techniques apportés

[QA] correct script postdeploy

---

assets/controllers/component_search_address.js
assets/controllers/form_signalement_erp_transport.js
assets/styles/app.scss
src/Entity/Enum/PlaceType.php
src/Form/SignalementTransportType.php
templates/front_signalement_erp/index.html.twig

#417    
* Divers correctif au niveau js, css et contenu
```
make npm-build
```

[FO] Retours formulaires ERP/Transports

---

templates/front/entreprises-labelisees.html.twig

#428    
Correction de l'affichage des filtres en responsive pour les entreprises labellisées

[Entreprises labellisées] Correction affichage des filtres responsive

---

src/Controller/Front/HomeController.php
templates/common/footer.html.twig
templates/front/mentions-legales.html.twig
templates/front/politique-de-confidentialite.html.twig

#456   
Ajout de la page Politique de confidentialité

[FO] Ajout de la page Politique de confidentialité

---

assets/styles/app.scss
templates/front_signalement_erp/index.html.twig
templates/front_signalement_transport/index.html.twig

#449    
Deux corrections sur les formulaires ERP et Transports 
- suppression du doublon d'identifiant sur label
- ajout du curseur sur tout le bouton d'upload de fichier

[FO - ERP et Transports] Corrections d'accessibilité sur les formulaires 

---

assets/controllers/form_signalement_front.js
templates/front_signalement/_partial_step_home.html.twig

#448    
Ajout d'un label pour le code postal
Scroll en haut de page quand erreur dans formulaire

[FO - Signalement] Corrections d'accessibilité

---

assets/styles/app.scss
grumphp.yml
templates/common/components/filters/filter-niveau-infestation.html.twig
templates/common/components/filters/filter-signalement-type.html.twig
templates/common/components/filters/filter-statut.html.twig
templates/common/components/filters/filter-territoire.html.twig
templates/front_suivi_usager/index.html.twig
templates/signalement_list/erp-transports.html.twig
templates/signalement_list/historique.html.twig
templates/signalement_list/hors-perimetre.html.twig
templates/signalement_list/signalements.html.twig
templates/signalement_view/tab-signalement.html.twig

#452 
#454    
Correction au niveau de l'accessibilité :
- zone dans une balise aside
- ajout de labels pour la recherche dans le BO

[BO] Améliorations accessibilité

---

assets/controllers/component_search_address.js
assets/controllers/component_search_commune.js
assets/styles/app.scss
templates/front_signalement/_partial_step_info_logement.html.twig
templates/front_signalement_erp/index.html.twig
templates/front_signalement_transport/index.html.twig
templates/signalement_create/tab-1.html.twig

#447    
Gestion du clavier pour la saisie d'adresses

[FO - Adresses] Accessibilité : Gestion du clavier pour la saisie d'adresse

---

templates/front/index.html.twig

#472   
Modifier : 
`"Stop-punaises.beta.gouv.fr est une plateforme numérique de l’Etat actuellement en test sur les départements des Bouches du Rhône (13) et du Rhône (69). "`
par :
`Stop-punaises.beta.gouv.fr est une plateforme numérique de l’Etat en cours de déploiement national.`
* Changement du twig

[FO - Contenu] Home Page

---

assets/controllers/form_signalement_front.js
migrations/Version20231124140038.php

#474   
Migration pour ouverture territoires 63 et 974
`make load-migrations`

[Territoires] Ouverture 63 et 974

---

.github/workflows/main.yml
.scalingo/nginx/server.location
composer.json
composer.lock

#477    
Même test que https://github.com/MTES-MCT/histologe/pull/1998 uniquement la partie iframe
Lock de phpstan et dama doctrine bundle pour réparer la CI

[Sécurité] Rendre le site invisible dans une iframe

---

.env
config/packages/security.yaml
src/Security/AppAuthenticator.php
templates/security/login.html.twig

#482 
Ajout d'une case à cocher se souvenir de moi sur le formulaire de connexion permettant de garder la connexion en mémoire durant un mois

Mettre en place la déconnexion automatique des sessions d'accès après une durée déterminée

---

templates/security/login.html.twig

#482
changement du libellé "Se souvenir de moi" en "Garder ma session ouverte pendant 1 mois."
* Liste des changements techniques apportés

changement de libellé "Se souvenir de moi"

---

templates/front_signalement/_partial_step_info_logement.html.twig
templates/front_signalement_erp/index.html.twig
templates/signalement_create/tab-1.html.twig

#489 
Ajout d'un label sur les champs "recherche d'adresse" ou il était manquant

Chaque champ formulaire a une étiquette

---

assets/styles/app.scss
templates/front/contact.html.twig

#505    
Corrections vis à vis de l'accessibilité :
- Précision que tous les champs sont obligatoires
- Mise en valeur des erreurs

[Front - Contact] Mention d'obligation et mise en valeur des erreurs

---

templates/base-back.html.twig
templates/base.html.twig
templates/cartographie/index.html.twig
templates/dashboard/index.html.twig
templates/entreprise_list/index.html.twig
templates/entreprise_view/index.html.twig
templates/front/contact.html.twig
templates/front/entreprises-labelisees.html.twig
templates/front/index.html.twig
templates/front/information.html.twig
templates/front/mentions-legales.html.twig
templates/front/signalement-type-list.html.twig
templates/front_signalement/index.html.twig
templates/front_signalement_erp/index.html.twig
templates/front_signalement_transport/index.html.twig
templates/front_suivi_usager/index.html.twig
templates/front_suivi_usager/messages_thread.html.twig
templates/security/login.html.twig
templates/security/reset_password.html.twig
templates/security/reset_password_link_sent.html.twig
templates/security/reset_password_new.html.twig
templates/signalement_create/index.html.twig
templates/signalement_list/erp-transports.html.twig
templates/signalement_list/historique.html.twig
templates/signalement_list/hors-perimetre.html.twig
templates/signalement_list/signalements.html.twig
templates/signalement_view/historique.html.twig
templates/signalement_view/not-authorized.html.twig
templates/signalement_view/not-found.html.twig
templates/signalement_view/signalement.html.twig

#488    
Inverser le titre et le nom du site
* Mise à jour des templates parent avec le nom du site - Stop punaises
* Mise à jour des templates enfant

[Accessibilité] Mise à jour titre des pages

---

templates/base-back.html.twig
templates/base.html.twig
templates/common/header-back.html.twig
templates/common/header.html.twig
templates/common/skiplink-back.html.twig
templates/common/skiplink.html.twig

#495    
Ajout du lien d'évitement du DSFR

[Accessibilité] Ajout du lien d'évitement du DSFR

---

CONTRIBUTING.md
README.md
templates/common/footer.html.twig

#522    
Informations pour la contribution au projet

[Sécurité] Informations pour la contribution au projet

---

migrations/Version20231219131305.php

#527   
Migration pour ouverture territoires 67, 75, 92 et 93
`make load-migrations`

[Territoires] Ouverture 67, 75, 92 et 93

---

migrations/Version20231220104819.php

#536    
Migration pour ouverture territoires Ain (01), Aveyron (12) et Lozere (48)
`make load-migrations`

[Territoires] Ouverture 01, 12, 48

---

templates/entreprise_list/index.html.twig
templates/front/contact.html.twig
templates/front/entreprises-labelisees.html.twig
templates/front/index.html.twig
templates/front/information.html.twig
templates/front/signalement-type-list.html.twig
templates/front_signalement/_partial_step_home.html.twig
templates/front_signalement/_partial_step_info_usager.html.twig
templates/front_signalement_erp/index.html.twig
templates/front_signalement_transport/index.html.twig
templates/signalement_create/tab-1.html.twig
templates/signalement_list/historique.html.twig
templates/signalement_list/signalements.html.twig

#497    
Modification de différents liens : label ou title, selon les cas

[Accessibilité] Modification de liens (label ou title)

---

tests/Functionnal/Controller/SignalementViewControllerTest.php

* Change l'année de référence des signalements dans les tests

Fix années de références des signalements dans les tests

---

assets/controllers/form_signalement_front.js
templates/front_signalement/_partial_recap.html.twig
templates/front_signalement/_partial_step_recommandation.html.twig

#492 
Ajout d'une partie "Récapitulatif" sur la page "Votre recommandation"
Possibilité de naviguer entre les différentes étapes du formulaire via la touché entré quand le focus et sur un input du formulaire

[Accessibilité] Ajouter d'un récap sur le formulaire signalement

---

assets/styles/app.scss
package-lock.json
package.json
src/Form/SignalementFrontType.php
templates/front/information.html.twig
templates/front/signalement-type-list.html.twig
templates/front_signalement/_partial_signalement_navigation_container.html.twig
templates/front_signalement/_partial_step_info_logement.html.twig
templates/front_signalement/_partial_step_insectes_larves_oeufs.html.twig
templates/front_signalement/_partial_step_insectes_punaises.html.twig
templates/front_signalement/_partial_step_traces_punaises_dejections.html.twig
templates/front_signalement_erp/index.html.twig
templates/front_signalement_transport/index.html.twig
templates/security/login.html.twig

#555
#557 
#565 
Corrections liées aux couleurs et aux ajustements d'affichage
Utilisation du template d'interface de connexion : https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles/page-de-connexion
`npm install`

[DSFR] Mise à jour en 1.11.0

---

templates/common/footer.html.twig
templates/common/header-back.html.twig
templates/common/header.html.twig

#559    
Mise à jour du header et du footer

[DSFR] Mise à jour du header et du footer

---

templates/front/signalement-type-list.html.twig
templates/front_signalement/_partial_step_home.html.twig
templates/front_signalement/index.html.twig
templates/front_signalement_erp/index.html.twig
templates/front_signalement_transport/index.html.twig

#566   
Mise en place de fils d'Ariane plutôt que lien de retour à l'accueil

[DSFR] Mise en place de fils d'Ariane plutôt que lien de retour à l'accueil

---

assets/styles/app.scss
templates/front/information.html.twig
templates/front_signalement/_partial_step_info_logement.html.twig
templates/signalement_create/tab-1.html.twig
templates/signalement_create/tab-2.html.twig

#568    
- Retrait de l'icone à gauche dans les champs d'adresse
- Utilisation de la balise `figure` pour afficher les images de la page Informations

[DSFR] Ajustements sur les formulaires et page d'information

---

templates/front_signalement/_partial_step_info_locataire.html.twig
templates/front_signalement/_partial_step_info_logement.html.twig
templates/front_signalement/_partial_step_info_problemes.html.twig
templates/front_signalement/_partial_step_info_usager.html.twig
templates/front_signalement/_partial_step_insectes_larves_intro.html.twig
templates/front_signalement/_partial_step_insectes_larves_oeufs.html.twig
templates/front_signalement/_partial_step_insectes_punaises.html.twig
templates/front_signalement/_partial_step_recommandation.html.twig
templates/front_signalement/_partial_step_resume.html.twig
templates/front_signalement/_partial_step_traces_punaises_dejections.html.twig
templates/front_signalement/_partial_step_traces_punaises_intro.html.twig
templates/front_signalement/_partial_step_traces_punaises_piqures.html.twig

#570   
Affichage complet de l'indicateur d'étapes dans le formulaire de signalement

[DSFR] Formulaire signalement : affichage de l'indicateur d'étape entier

---

assets/styles/app.scss
templates/front_signalement/_partial_step_traces_punaises_piqures.html.twig

#568   
Retours de Mathilde suite aux tests DSFR :
- augmenter les marges des boutons radio
- ajuster la zone d'upload des fichiers dans le formulaire de signalement

[DSFR] Modification affichage formulaire

---

templates/front/information.html.twig

#600    
Suite à l'audit
- suppression de l'attribut `role` sur les balises `figure`
- déplacement de la balise `button` autrement qu'en enfant direct de la balise `figure`

[Accessibilité - Informations] Correction code HTML non valide

---

templates/front/index.html.twig
templates/front/information.html.twig

#585    
Utilisation du composant DSFR pour afficher la vidéo sur la page d'accueil et la page Informations

[Accessibilité - Vidéo] Utilisation du composant DSFR

---

assets/controllers/component_search_address.js
assets/styles/app.scss
templates/front_signalement/_partial_step_info_logement.html.twig

#613    
Remplacer lien par un bouton (étape saisie adresse)
* Mise à jour balise html et sélecteur js associé

[Accessibilité - Audit] [Formulaire signalement - 6.1] Liens explicites 

---

assets/controllers/form_signalement.js
assets/styles/app.scss
templates/signalement_create/tab-1.html.twig
templates/signalement_create/tab-2.html.twig

#661   
Remplacement des liens par des boutons lors de la création d'un signalement historique dans le BO

[Accessibilité - BO Signalement] Remplacement des liens par des boutons

---

assets/controllers/component_search_address.js
assets/styles/app.scss
templates/front_signalement/_partial_step_info_logement.html.twig
templates/front_signalement/_partial_step_recommandation.html.twig
templates/security/login.html.twig

#616   
Transformation du lien qui permet de passer en mode saisie manuelle pour l'adresse : remplacement par un bouton toggle (permettant de revenir à la saisie auto)
Modification du titre du lien de fin vers Histologe

[Accessibilité - Formulaire signalement] Modification des liens

---

templates/base-back.html.twig
templates/front/contact.html.twig
templates/front_suivi_usager/index.html.twig
templates/security/reset_password.html.twig
templates/security/reset_password_link_sent.html.twig
templates/security/reset_password_new.html.twig
templates/signalement_list/historique.html.twig
templates/signalement_view/signalement.html.twig

#654 
Ajout du role="status" sur les message flash et autres messages ayant cette finalité

[Accessibilité - Audit] [BO Ajout signalement - 7.5] Transformer les messages en statut

---

templates/signalement_create/tab-1.html.twig
templates/signalement_create/tab-2.html.twig

#657 
Ajout de fieldsets sur le formulaire de signalement BO

[Accessibilité - Audit] [BO Ajout signalement - 11.5] Regrouper les champs de formulaire 

---

Makefile
assets/controllers/list_employes.js
assets/controllers/list_entreprises.js
assets/controllers/list_signalement.js
templates/common/footer.html.twig
templates/front/contact.html.twig
templates/front/index.html.twig
templates/front/information.html.twig
templates/front_signalement/_partial_step_info_usager.html.twig

#698    
Revue de liens
* Mise à jour lien statique
* Mise à jour lien dynamique (Datatable)

[Accessibilité - Audit] [Correction des liens - 6.1 ET 13.5]

---

assets/controllers/form_signalement.js
src/Form/SignalementHistoryType.php
templates/signalement_create/index.html.twig
templates/signalement_create/tab-1.html.twig
templates/signalement_create/tab-2.html.twig

#702    
Correction des titres et champs dans le formulaire d'ajout de signalement historique
Je n'ai pas repris sa proposition de titres, car ceux de niveau 3 sont déjà des légendes de fieldsets

[BO - Signalement] Correction des titres et champs dans le formulaire d'ajout d'historique

---

templates/front/_partial_video.html.twig
templates/front/index.html.twig
templates/front/information.html.twig

#485    
Ajout de la transcription sous la vidéo sur les pages Accueil et Informations

[Accessibilité] Ajout de la transcription en-dessous de la vidéo

---

.env
.env.sample
.github/workflows/main.yml
CONTRIBUTING.md
README.md
templates/front/accessibilite.html.twig
templates/front/index.html.twig

#741    
Ajustement des textes et configurations qui font référence à beta.gouv.fr

[CONF] Passage de beta.gouv.fr à gouv.fr

---

templates/front/index.html.twig

#760
Remplacement de "l'Etat Français" par "l'administration française" sur la homepage

[FO] Remplacer etat français par administration française

---

templates/front/index.html.twig
templates/front_signalement/_partial_step_info_intro.html.twig

#778   
Correction de 2 fautes d'orthographe à "débarrasser"

[FO] Correction de fautes d'orthographe

---

assets/controllers/component_search_address.js

#695
Description de la modification apportée
* Liste des changements techniques apportés

[WIP][FO - Signalement] Pas d'Auto completion Adresse - Mobile

---

config/packages/twig.yaml
templates/common/header-back.html.twig

#769   
Intégrer un lien vers la FAQ dans le BO
* Changement du twig

[BO - Entreprises] Intégrer lien vers FAQ

---

composer.lock

#805    
Incomptabilité de version entre dépendances cache et redis
* Mise à jour des dépendances `composer update`

[Déploiement] Mise à jour des dépendances dont le composant cache

---

assets/styles/app.scss
src/Command/SendRemindersCommand.php
src/Controller/EntrepriseViewController.php
src/Controller/Front/SignalementController.php
src/Controller/Front/SuiviUsagerViewController.php
src/Controller/SignalementMessageController.php
src/Entity/Entreprise.php
src/EventSubscriber/SignalementClosedSubscriber.php
templates/entreprise_list/index.html.twig
templates/front_suivi_usager/messages_thread.html.twig
templates/front_suivi_usager/modal-choice-estimation.html.twig
tests/Functional/Controller/Front/SuiviUsagerViewControllerTest.php

#804
- Ajout d'une feature SA permettant d'archiver/désarchiver des entreprises (via la modification du statut de leur user)
- Retrait de l'envoie des notification email pour les entreprise archivées/inactives
`make npm-build`

[QA] Archiver une entreprise

---

package-lock.json
package.json
templates/common/footer.html.twig
templates/front/accessibilite.html.twig
templates/front/mentions-legales.html.twig
templates/front/politique-de-confidentialite.html.twig

#836   
Mise à jour des packages npm (notamment DSFR)
* Suite à mise à jour DSFR, ajustement des tableaux `fr-table`
`npm install`

[Tech] Mise à jour npm et DSFR
