- src/EventSubscriber/EntrepriseUpdatedSubscriber.php
Lié [#648](https://github.com/MTES-MCT/histologe/issues/648)
Rappel un user rôle_admin est aussi un rôle_entreprise de part la hiérarchie des rôles donc la condition est **tout ceux qui ne sont pas admin**
> Revue condition déconnexion après mise à jour mail

- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Loader/LoadSignalementData.php
- src/EventSubscriber/MessageAddedSubscriber.php
- src/Manager/EventManager.php
Lié à https://github.com/MTES-MCT/stop-punaises/issues/262
Quand il y a des échanges de messages, il faut un événement pour l'usager, pour l'entreprise et pour l'admin
> add event for admin when messages between usager and entreprise

- templates/front_suivi_usager/index.html.twig
> Désactivation du bouton pour trouver une entreprise si l'usager est dans un territoire inactif

- assets/controllers/form_signalement_front.js
> Correction parcours quand on saisit un territoire inactif

- templates/front_suivi_usager/index.html.twig
Fix for : https://github.com/MTES-MCT/stop-punaises/issues/289
> Bloquer le passage pour les pros pour les signalements sur les logements sociaux

- assets/styles/app.scss
#301    
Correction du double affichage d'icone de calendrier sur les champ fr-input de type date
> Correction du double affichage d'icone de calendrier

- src/Repository/InterventionRepository.php
- templates/common/components/signalement-detail-evenements.html.twig
- templates/front_suivi_usager/index.html.twig
#296 
Ouverture automatique des modales dans la page usager après réception notification de résolution de problème
Faire le parcours d'un signalement jusqu'à ce qu'une entreprise déclare le problème résolu
Changer la date de résolution en bas de données (donnée `Intervention`, champ `resolved_by_entreprise_at`)
Jouer la commande d'envoi de notifications de rappel `make console app="send-reminders"`
Faire le parcours d'un signalement en auto-traitement
Changer la date de création du signalement (donnée `Signalement`, champ `created_at`)
Jouer la commande d'envoi de notifications de rappel `make console app="send-reminders"`
> Ouverture automatique de modales de résolution de problème

- templates/common/components/signalement-procedure.html.twig
#291  
Correction des statuts de signalement dans la liste BO pour les admins
> Correction des statuts de signalement dans la liste BO pour les admins

- src/EventSubscriber/InterventionUsagerRefusedSubscriber.php
#304    
Modification pour que la notification qui affiche "L'usager a refusé toutes les estimations des entreprises" ne s'affiche que pour les admins, et pas pour les entreprises.
Créer un signalement, faire des estimations avec 2 entreprises, refuser les deux estimations depuis la vue Usager.
> Correction pour la notification "Plus d'estimation" uniquement pour admin

- assets/controllers/component_search_address.js
- cypress/e2e/signalement-add-scenarii.cy.js
- cypress/fixtures/user.json
- cypress/src/front/front-signalement-geoloc.cy.js
- migrations/Version20230609122239.php
- src/Command/GeolocateCommand.php
- src/Entity/Signalement.php
- src/Form/SignalementFrontType.php
- src/Form/SignalementType.php
- templates/front_signalement/_partial_step_info_logement.html.twig
- templates/signalement_create/tab-1.html.twig
#318    
Enregistrement de la géolocalisation pour les signalements. Première étape nécessaire pour la cartographie
* Ajout d'un champ geoloc à la table signalement
* Création d'une commande qui ajoute la géolocalisation à tous les signalements existants
* Ajout de paramètre au formulaire front pour enregistrer la localisation lors de la création d'un nouveau signalement
- [] Jouer la commande "`symfony console app:geolocate`" et vérifier en base que les coordonnées ont bien été ajoutées aux signalements existants
- [] Créer un nouveau signalement, et vérifier en base que sa géolocalisation a bien été enregistrée
> Initialiser les données de localisation (longitude, latitude) pour les signalements : données en base et migration

- src/Command/ImportSignalementCommand.php
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Repository/SignalementRepository.php
- src/Service/Import/Signalement/SignalementImportLoader.php
- src/Service/Signalement/ReferenceGenerator.php
#325   
Hotfix de la commande qui permet d'importer les signalements historiques d'une entreprise, en fonction de son uuid.
cf doc ici https://github.com/MTES-MCT/stop-punaises/wiki/Import-signalements-historiques
* Fix sur la création de référence en prenant bien l'année de création d'un signalement
- 645ba1e3ccc7a 	EPUR
- 645ba4262be42 	CANEM DETECT
- 63b6c306ec8bc 	Antipesti 
- 63b6c1f37473d 	A3DS
- 63b6c29ebf3a9 	A4D Sanitation
- 645ba3835a509 	COTIERE HYGIENE ASSAINISSEMENT
- 63b6c22f88ef0 	DKM Experts
- 63bd8aa4bdf8d 	Eco flair 
- 63b6c20ec2c3e 	ELIS Pest Control 
- 645ba251e316f 	 ESIAN NUISIBLES
- 645ba299ea088 	GAME OVER PRO
- 645ba4550c379 	LA CAMDA-Rhône
- 645ba483bcd06 	MS Plus
- 645ba35297404 	NGAN 69 
- 645ba3e85de3e 	OMNYS SOLUTION 
- 63bd8a72e16ed 	Rentokil Initial 13
- …
> [BO - Signalements historiques] hotfix sur la génération de référence

- public/js/maps.js
#320    
Rendre les points plus visibles
Passage des signalements "traces" à une intensité de 0,5 au lieu de 0,3
Changement du maxZoom de la carte de chaleur qui était par défaut égal au maxZoom de la carte (donc 18), il est maintenant à 15 et il correspond au niveau de zoom auquel les points sont les plus intenses
> [BO - Cartographie] Rendre les points plus visibles sur la carte de chaleur 

- templates/front_suivi_usager/modal-toujours-punaises.html.twig
#236   
Après 45 jours, les signalements qui ont opté pour l'auto-traitement reçoivent un mail de rappel pour demander où ils en sont.
Ce mail conduit à la page de suivi.
Si le problème n'est pas résolu, on proposait soit d'arrêter la procédure, soit de faire appel à un pro.
La correction consiste à masquer la partie "appel à un pro" pour les signalements sur des territoires inactifs.
> [FO - Signalement] Ne pas proposer de faire un appel à un pro pour les signalements dans les territoires inactifs

- templates/front_suivi_usager/index.html.twig
#330    
A J+45, si l'usager a choisi auto-traitement, on lui demande une mise à jour par mail.
L'usager peut alors cloturer sa demande.
Une fois la demande cloturée, la modale de demande continuait à s'afficher en boucle.
> [FO - Signalement] Ne pas afficher la modale de demande d'information si le signalement est fermé

- src/Controller/Front/SignalementController.php
- src/Controller/Front/SuiviUsagerViewController.php
- src/Controller/SignalementResolveController.php
- src/Controller/SignalementViewController.php
- src/Entity/Signalement.php
- templates/front_suivi_usager/index.html.twig
#331   
Si un administrateur ferme un signalement, on change l'uuid public sans l'envoyer à l'usager pour désactiver l'accès
> [FO - Suivi usager] Désactivation de l'accès à la page après cloture par administrateur

- migrations/Version20230810133819.php
- src/Command/SendRemindersCommand.php
- src/Entity/Intervention.php
- src/Repository/InterventionRepository.php
- src/Service/Mailer/MailerProvider.php
- src/Service/Mailer/Template.php
#337    
Si une intervention est toujours en cours 60 jours après l'acceptation d'une estimation par l'usager, on envoie un notification à l'entreprise
* Ajout template
* Modification de la commande d'envoi de notifications
> [CRON] Envoi de notifications aux entreprises 60 jours après acceptation d'estimation par l'usager

- templates/signalement_view/signalement.html.twig
#308   
Correction pour l'accès pour l'entreprise au bouton de cloture de signalement si l'estimation est en attente
> [BO - Signalement] Correction pour l'accès au bouton de cloture de signalement si l'estimation est en attente

- src/Command/SendRemindersCommand.php
- src/Repository/SignalementRepository.php
#336    
Cloture automatique des signalements en traitement pro après 30 jours d'inactivité
> [CRON] Cloture automatique des signalements en traitement pro après 30 jours d'inactivité

- templates/front_suivi_usager/index.html.twig
Correction de l'affichage des modales dans le suivi usager
> [Suivi usager] Correction de l'affichage des modales

- assets/controllers/form_signalement_front.js
#379    
Ajout de test pour les signalement sur les territoires fermés pour avoir des champs renseignés
> [FO - Signalement] Ajout de test pour les signalement sur les territoires fermés

- src/Controller/Front/EntreprisesPubliquesController.php
#366    
Correction de l'affichage pour les entreprises labellisées dans les DOM
`make console app="import-entreprise-publique"`
> [FO - Entreprises labellisées] Correction de l'affichage pour les entreprises dans les DOM

- .env
- .env.sample
- .github/workflows/main.yml
- assets/controllers/form_signalement_front.js
- config/services.yaml
- src/Controller/Front/SignalementController.php
- src/Controller/SignalementCreateController.php
- src/Entity/Signalement.php
- src/Form/SignalementFrontType.php
- src/Form/SignalementHistoryType.php
- src/Service/Mailer/MailerProvider.php
- src/Service/Mailer/MessageFactory.php
- tests/Functionnal/Controller/Front/SignalementControllerTest.php
- tests/Functionnal/Controller/SignalementControllerTest.php
- tests/SessionHelper.php
#385    
Des mails s'envoient sans destinataires. Remonter à la source du problème avec une validation non présente sur le front (corrigé dans https://github.com/MTES-MCT/stop-punaises/pull/390/files)
BIen que la validation ai été ajouté sur ce formulaire, une double validation est nécessaire. 
* Validation géré par des groupe de validation pour le formulaire front et back 
* Création d'une boite mail inconnu afin de recevoir les messages sans destinataire
Ajout d'une nouvelle variable d'environnement
`INCONNU_EMAIL=inconnu@stop-punaises.beta.gouv.fr`
~~- [ ] Supprimer l'email occupant sur le signalement dans la base et envoyer un message via la plateforme à l'usage (vérifier qu"on recoit bien le mail)~~
> [QA] Gestion des contrainte de validations du aux erreurs d'envoi d'email

- assets/controllers/list_signalement.js
- config/packages/security.yaml
- src/Controller/DashboardController.php
- src/Controller/Front/SignalementController.php
- src/Controller/SignalementListController.php
- src/Entity/Enum/SignalementType.php
- src/Entity/Signalement.php
- src/Manager/SignalementManager.php
- src/Repository/SignalementRepository.php
- src/Twig/AppExtension.php
- src/Twig/EnumExtension.php
- templates/bundles/TwigBundle/Exception/error.html.twig
- templates/bundles/TwigBundle/Exception/error403.html.twig
- templates/bundles/TwigBundle/Exception/error404.html.twig
- templates/common/components/filters/filter-signalement-type.html.twig
- templates/dashboard/index.html.twig
- templates/dashboard/nav.html.twig
- templates/signalement_list/erp-transports.html.twig
- templates/signalement_list/modal-signalement-erp-transports.html.twig
#373    
Création de la liste des signalements ERP/Transports https://github.com/MTES-MCT/stop-punaises/wiki/listes-de-signalements#signalements-erp-et-transports
Création du menu et de la carte sur le dashboard pour les admins
* Création des templates twigs pour la liste, la modale et le filtre
* Ajout d'un item dans le menu et d'une carte dans le dashboard
* Ajout d'extensions twig pour le bon affichage
* Ajout d'une fonction dans le repository pour récupérer les signalements ERP et transports, et modification d'autres fonctions
* Ajout d'une route erp-transports
`make create-db`
> [BO] Créer le listing ERP / transport dans le BO 

- package-lock.json
- package.json
#398
Depuis mercredi, tous les déploiements sont en échec
https://dashboard.scalingo.com/apps/osc-fr1/stop-punaises/deploy/list
Nous remarquons que le build utilise une version 21.0
Il s’avère que cette version est sorti mardi dernier 
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V21.md#21.0.0
Nos environnements de developpement ainsi qu'Histologe sont sur une version LTS  de node (voir https://github.com/MTES-MCT/histologe/pull/1011)
* MAJ du package caniuse-lite
* Forcer la version de node dans le package.json
> [CD] Forcer la version de node à 18.18.2 LTS

- .docker/nginx/default.conf
- .scalingo/nginx/server.location
- assets/controllers/form_signalement_erp_transport.js
- assets/styles/app.scss
- package-lock.json
- templates/front_signalement_erp/index.html.twig
- templates/front_signalement_transport/index.html.twig
#374 
#375    
Ajout d'un bloc de configuration Nginx pour laisser symfony servir toute URL commençant par "/_up/" suivie de n'importe quel nombre de caractères, puis se terminant par l'extension ".jpg", ".jpeg" ou ".png".
**L'ordre des bloc est important  il se situe avant le bloc qui sert les assets pour mise en cache**
* Mise à jour de la conf nginx
* Mise à jour UI (icones, bouton d'upload, radio, ect..)
* Limiter les fichiers à 10 MB
```
make build
```
> [FO] Formulaire ERP / Transport

- assets/controllers/form_signalement_front.js
- src/Controller/Front/SignalementController.php
- src/Form/SignalementErpType.php
- src/Form/SignalementFrontType.php
- src/Form/SignalementHistoryType.php
- templates/front_signalement/_partial_step_home.html.twig
#350 
#383    
Ajout de contraintes sur le code postal pour éviter 2 erreurs sentry
* Ajout de contraintes dans les FormType
* Ajout de vérification js
> [QA] Ajout de contraintes sur le code postal

- assets/controllers/list_entreprises_publiques.js
- migrations/Version20231020131118.php
- scripts/postdeploy.sh
- scripts/upload-s3.sh
- src/Command/ImportEntreprisePubliqueDetectionCanineCommand.php
- src/Controller/Front/EntreprisesPubliquesController.php
- src/Entity/EntreprisePublique.php
- src/Factory/EntreprisePubliqueFactory.php
- src/Manager/EntreprisePubliqueManager.php
- src/Repository/EntreprisePubliqueRepository.php
- src/Service/Import/EntreprisePublique/EntreprisePubliqueImportLoader.php
- src/Service/Import/EntreprisePublique/EntreprisePubliqueImportMapper.php
- templates/front/entreprises-labelisees.html.twig
#372    
Intégrer les entreprises manquantes
Distinguer dans l'annuaire la détection et l'intervention
*  faire évoluer l'entité entreprise_publique pour ajouter isIntervention, isDetectionCanine, isProOnly (3 booléens)
*  dans la migration, attribuer les valeurs 1, 0, 0 à ces 3 nouvelles informations
*  création d'une commande qui parcourt le fichier des entreprises de détection canine :  si l'entreprise existe déjà lui mettre les bonnes valeurs pour isIntervention, isDetectionCanine, isProOnly (0, 1 et selon le fichier) (pour chaque occurence), et si l'entreprise n'existe pas la créer dans les départements adéquats.
*  faire évoluer l'affichage de la page entreprises-labellisees pour ajouter les informations detection/intervention et "only pro" dans l'encart et pour créer un filtre
> [Annuaire Entreprise] Détection Canine

- assets/controllers/form_signalement_erp_transport.js
#417    
Lors d'upload de fichier une par une, seule la dernière image est uploadé ignorant toute celle uploadé avant.
* Centraliser des fichiers à travers un tableau
* Reconstruire les input de type file manuellement à partir du tableau
```
make npm-build
```
> [FO] Gestion de la soumission des téléversements d'image une par une

- assets/controllers/form_signalement_erp_transport.js
#409
Description de la modification apportée
* Ajout du focus
> [FO] Formulaire ERP - Focus sur le champs autocompletion adresse en cas d'erreur

- Makefile
- src/Controller/SignalementViewController.php
- src/Repository/InterventionRepository.php
- tests/Functionnal/Controller/SignalementViewControllerTest.php
#384    
On a actuellement une erreur sentry, car certains signalements ont plusieurs interventions identiques pour la même entreprise.
Je n'ai pas réussi à reproduire la création de ces interventions identiques. Mais si on en suplique une en base, on reproduit l'erreur en affichant la fiche signalement dans le BO avec l'entreprise concernée
* Dans la route `app_signalement_intervention_accept`, on vérifie d'abors s'il n'existe pas déjà une intervention pour ce signalement*entreprise avant d'en créer une
* Dans le repository on ne récupère que la première des interventions si elles sont doublonnées
> [QA] plusieurs interventions retournées quand 1 attendue

- assets/controllers/component_search_commune.js
- src/Form/SignalementTransportType.php
- templates/signalement_list/modal-signalement-erp-transports.html.twig
- tests/Functionnal/Controller/Front/SignalementTransportControllerTest.php
#421    
Ne pas rendre Ligne de transport obligatoire lorsque autre est sélectionné
* Ajout d'un listener au `PRE_SUBMIT` afin de supprimer la contrainte NotBlank
> [FO - Signalement] Ligne de transport non obligatoire lorsque autre est selectionné

- assets/controllers/component_search_commune.js
- assets/controllers/form_signalement_erp_transport.js
- src/Controller/Front/SignalementErpController.php
- src/Controller/Front/SignalementTransportController.php
- src/Entity/Signalement.php
- src/Form/SignalementErpType.php
- src/Form/SignalementTransportType.php
- src/Service/Signalement/SignalementDateTimeProcessing.php
- templates/signalement_list/modal-signalement-erp-transports.html.twig
- tests/Functionnal/Controller/Front/SignalementErpControllerTest.php
- tests/Functionnal/Controller/Front/SignalementTransportControllerTest.php
#422    
Un usager ne doit pas pouvoir soumettre un signalement avec une date dans le futur 
* Ajout contrainte et traitements pour la gestion des dates
```php
make npm-build
```
> [FO - ERP & transport] Ajouter vérification sur la date

- src/Controller/Front/SuiviUsagerViewController.php
- tests/Functionnal/Controller/Front/SuiviUsagerViewControllerTest.php
#423    
Envoyer un mail aux entreprises quand un signalement bascule d'autotraitement à prise en charge profressionnelle
* Modification de la route `app_signalement_switch_pro`
* Ajout de tests sur le controller
> [BO - Email] Envoyer un mail aux entreprises quand un signalement bascule

- templates/front/entreprises-labelisees.html.twig
#429    
Correction de l'affichage du lien du site web des entreprises labellisées
> [Entreprises labellisées] Correction de l'affichage du lien

- templates/signalement_view/signalement.html.twig
#424   
Bouton de clôture masqué pour l'entreprise si l'estimation a été refusée par l'usager
> [BO - Signalement] Bouton de clôture masqué pour l'entreprise si l'estimation a été refusée par l'usager

- src/DataFixtures/Files/Signalement.yml
- src/Form/SignalementHistoryType.php
- src/Twig/AppExtension.php
#437    
Dans le formulaire d'ajout/édition de signalement BO, un enum supporte mal les valeurs nulles.
J'ai ajouté un test.
Normalement, j'imagine que la méthode pour reproduire est 
- d'être connecté en tant qu'entreprise
- d'aller sur un signalement front qui a un niveau d'infestation nul
- de le marquer comme traité
Mais je n'ai pas réussi à reproduire l'erreur de base qui a été relevée par Sentry : https://sentry.incubateur.net/organizations/betagouv/issues/71873/?query=is%3Aunresolved&referrer=issue-stream
> [QA - Sentry] Ajout d'un test de valeur pour récupérer le niveau d'infestation dans le formulaire BO

- .env
- .env.sample
- config/services.yaml
- src/Controller/Front/HomeController.php
- src/Controller/Front/SignalementErpController.php
- src/Controller/Front/SignalementTransportController.php
- templates/front/signalement-type-list.html.twig
#440    
Ajout de feature flipping sur le nouveau workflow de signalement :
- ne pas proposer les 3 types de formulaire mais donner accès à un seul
Dans `.env.local`
`FEATURE_THREE_FORMS_ENABLE = 1`
Dans `.env.local`
`FEATURE_THREE_FORMS_ENABLE = 0`
> [Front - Signalement] Ajout de feature flipping sur le nouveau workflow de signalement

- src/Controller/Front/EntreprisesPubliquesController.php
- src/DataFixtures/Files/Territoire.yml
- src/Service/Signalement/ZipCodeProvider.php
- tests/Functionnal/Service/ZipCodeProviderTest.php
#434    
Correction de la prise en compte des codes postaux corse
> [Front - Signalement] Correction des signalements sur un CP corse

- src/Controller/Front/HomeController.php
#466   
Ajout de cache navigateur (10 minutes) sur les pages statiques :
- home
- informations
- mentions légales, etc.
> [Front] Ajout de cache navigateur sur les pages statiques

- src/Form/EmployeType.php
- templates/entreprise_view/modal-edit-employe.html.twig
#453   
Modification des ids de champs pour éviter les doublons dans les formulaires d'employés
> [BO - Entreprises] Modification des ids de champs d'employé pour éviter les doublons

- Makefile
- docker-compose.tools.yml
- docker-compose.yml
- package-lock.json
- tools/k6/k6-50000.js
#468   
Ajout de K6 pour faire des tests de montée en charge
* Ajout du docker de K6
* Modification du fichier `Makefile`
* Fichier js de configuration faisant 50 000 requêtes
`make build`
> [OPS] Ajout de K6 pour faire des tests de montée en charge

- src/EventSubscriber/InterventionEntrepriseCanceledSubscriber.php
- src/EventSubscriber/InterventionUsagerAcceptedSubscriber.php
- src/Repository/EventRepository.php
#250    
Lorsqu'un usager accepte une estimation, on ne souhaite pas que les autres entreprises aient accès au nom de l'entreprise acceptée.
Lorsqu'une entreprise annule son intervention, on ne souhaite pas que les autres entreprises y aient accès non plus.
Conseil : utiliser 2 navigateurs et navigateurs privés pour faciliter les tests
Pour les 2 points suivants, si besoin, changer le territoire d'intervention de l'entreprise une fois connecté, pour pouvoir traiter le signalement, selon l'adresse.
> [BO - Signalement] Anonymisation des noms d'entreprise pour les autres entreprises

- config/services.yaml
#471    
Augmentation du temps (1h au lieu de 10min) avant que le token d'inscription ne soit plus valide
> [BO - Entreprises] Augmentation du temps avant que le token d'inscription ne soit plus valide

- src/Command/ReinitAdminPasswordsCommand.php
- src/Repository/UserRepository.php
#480    
Commande de remise à zero des mots de passe administrateurs
> [Sécurité] Commande de remise à zero des mots de passe administrateurs

- templates/cartographie/curseur.html.twig
- templates/common/components/progression-signalement.html.twig
- templates/dashboard/index.html.twig
- templates/front/contact.html.twig
- templates/front_signalement_erp/index.html.twig
- templates/front_signalement_transport/index.html.twig
- templates/front_suivi_usager/index.html.twig
- templates/signalement_view/tab-intervention.html.twig
- templates/signalement_view/tab-logement.html.twig
- tests/Functionnal/Controller/Front/SuiviUsagerViewControllerTest.php
#490    
Revue de toutes les pages afin de vérifier la hiérarchie des titres: 
Que chaque pages aient un titre `<h1>` et qu'une hiérarchie soit bien respectée et que les modales aient un titre (`<h1>` en l'occurrence)
- [https://stop-punaises.beta.gouv.fr/](https://stop-punaises.beta.gouv.fr/)
- [https://stop-punaises.beta.gouv.fr/information](https://stop-punaises.beta.gouv.fr/information)
- [https://stop-punaises.beta.gouv.fr/contact](https://stop-punaises.beta.gouv.fr/contact)
- [https://stop-punaises.beta.gouv.fr/login](https://stop-punaises.beta.gouv.fr/login)
- [https://stop-punaises.beta.gouv.fr/signalement](https://stop-punaises.beta.gouv.fr/signalement) 
- [https://stop-punaises.beta.gouv.fr/mentions-legales](https://stop-punaises.beta.gouv.fr/mentions-legales) 
- …
> [Accessibilité] Rendre la hiérarchie des titres cohérente (H1 sur toutes la pages et pas de saut)

- templates/bundles/TwigBundle/Exception/error.html.twig
- templates/bundles/TwigBundle/Exception/error403.html.twig
- templates/bundles/TwigBundle/Exception/error404.html.twig
- templates/common/components/signalement-detail.html.twig
- templates/common/header-back.html.twig
- templates/common/header.html.twig
- templates/front/index.html.twig
- templates/signalement_view/tab-intervention.html.twig
#487    
Ajout des de texte alternatifs manquant sur les images dont le logo.
[D'après Web-Aim, l'organisation qui promeut l'accessibilité sur le Web](https://webaim.org/techniques/alttext/#logos), un texte pour le logo est à prévoir mais sans le mot logo.
* Ajout des textes sur les balises alt
> [Accessibilité] Ajouter une balise alt à toutes les images

- Makefile
- migrations/Version20231117204437.php
- migrations/Version20231124140038.php
- migrations/Version20231213081418.php
- src/Command/ImportCompteUtilisateurCommand.php
- src/Service/Import/CompteUtilisateur/CompteUtilisateurLoader.php
- tests/Functionnal/Service/Import/CompteUtilisateur/CompteUtilisateurLoaderTest.php
#519    
Dans le cadre du déploiement nationale, de nouveaux territoires doivent être ouvert et de nouveaux compte entreprises doivent être ajouté ou **mise à jour si nouveaux territoire** sur la plateforme
Les nouveaux territoires
03, 05, 10, 11, 14, 15, 16, 22, 25, 26, 27, 30, 32, 36, 39, 41, 53, 56, 57, 61, 65, 68, 74, 76, 77, 78, 79, 80, 82, 83, 85, 86, 88, 90, 91, 94, 95
* Mise à jour de la commande d'import de compte entreprise
* Ajout d'une migration pour l'ouverture de nouveaux territoires
Le nouveau CSV est deja sur staging `entreprises-utilisateurs-1.csv`
Vider la base de donnée et exécution de la nouvelle migration
```bash
make create-db
```
Une fois la table territoire crée, exécutez cette migration
```
make execute-migration name=Version20231213081418 direction=down
make …
```
> [Ouverture] Ouverture nouveaux territoires et gestion ajout territoire intervention pour compte deja existant

- assets/styles/app.scss
- templates/entreprise_list/index.html.twig
- templates/entreprise_view/index.html.twig
- templates/signalement_list/erp-transports.html.twig
- templates/signalement_list/historique.html.twig
- templates/signalement_list/hors-perimetre.html.twig
- templates/signalement_list/signalements.html.twig
#501   
Mise en place d'une couleur de fond blanche pour les listes du BO, afin de faire ressortir les couleurs avec peu de contrastes vis à vis du gris.
Les inputs repassent en gris classique, à l'inverse.
> [BO - Listes] Mise en place d'une couleur de fond blanche

- assets/styles/app.scss
- templates/common/components/signalement-detail-evenements.html.twig
- templates/front_signalement/_partial_step_insectes_larves_oeufs.html.twig
- templates/front_signalement/_partial_step_insectes_punaises.html.twig
- templates/front_signalement/_partial_step_traces_punaises_dejections.html.twig
- templates/front_signalement/_partial_step_traces_punaises_piqures.html.twig
#503    
Sur Firefox, quand on passait en `Zoom Text Only`, le `i` qui affiche la modale "plus d'informations" s'affichait mal.
Avec le recul, en terme d'accessibilité, ça ne semblait de toute façon pas le plus évident des liens.
J'ai vu avec Mathilde pour remplacer par un lien `Plus d'informations` complet.
> [FO - Signalement] Modification lien plus d'informations

- assets/controllers/list_employes.js
- assets/controllers/list_entreprises.js
- assets/controllers/list_signalement.js
- assets/styles/app.scss
- package-lock.json
- package.json
- templates/base-back.html.twig
- templates/entreprise_list/index.html.twig
- templates/entreprise_view/index.html.twig
- templates/signalement_list/erp-transports.html.twig
- templates/signalement_list/historique.html.twig
- templates/signalement_list/hors-perimetre.html.twig
- templates/signalement_list/signalements.html.twig
- webpack.config.js
#502   
Rendre les listes du BO responsive (signalements, entreprises, usagers)
* Utilisation du package datatables.net-responsive-dt
* Ajout de l'option `responsive: true,` sur les 3 types de listes
* Ajout de la classe nowrap sur toutes les datatables
* Ajout d'une classe fr-hidden sur les <span> cachés servant à la recherche (pour compenser la suppression du `display: none;` dans app.scss qui ne permettait pas la visibilité des infos supplémentaires d'une ligne)
```
make npm-install
npm run watch
```
> [Accessibilité] Rendre les listes du BO responsive

- assets/styles/app.scss
#507 
Amélioration de l'affichage de pages lors de la navigation en mode contraste élevé de Windows
* Ajout du quick fix et autres règles CSS
> [Accessibilité] Implémenter le quick-fix sur le contraste élevé

- src/Controller/Front/HomeController.php
- templates/common/footer.html.twig
- templates/front/accessibilite.html.twig
- templates/sitemap/index.html.twig
#520 
Ajout de la page de déclaration d'accessibilité.
Ajout d'un lien dans le footer vers cette page
> [Accessibilité] Ajout d'un lien dans le footer vers une page de déclaration d'accessibilité

- config/services.yaml
- src/Command/InitSignalementEventsCommand.php
- src/Controller/Front/SignalementController.php
- src/Controller/Front/SuiviUsagerViewController.php
- src/Event/SignalementAddedEvent.php
- src/EventSubscriber/SignalementAddedSubscriber.php
- src/Manager/EventManager.php
- src/Twig/AppExtension.php
- src/Utils/FileHelper.php
- templates/front/index.html.twig
- templates/front_suivi_usager/index.html.twig
- tests/Unit/Utils/FileHelperTest.php
#500    
Ajouter le poids des pdfs. La plupart des pdf sont envoyés par mail, j'ai ajouté le poids sur la page de suivi usager.
* Modification du controller et du twig pour afficher le poids
* Ajout d'une extension Twig  pour le formatage du poids
> [Accessibilité] Mettre le poids des pdf à télécharger

- templates/front/information.html.twig
#563   
Les deux images de la page Informations contiennent beaucoup de texte. On améliore le remplissage de la balise alt de ces deux images.
> [DSFR] Ajout de contenu plus détaillé pour les deux images de la page Informations

- assets/styles/app.scss
- templates/front_signalement/_partial_signalement_navigation_container.html.twig
- templates/front_signalement/_partial_step_autotraitement_info.html.twig
- templates/front_signalement/_partial_step_home.html.twig
- templates/front_signalement/_partial_step_professionnel_info.html.twig
- templates/front_signalement/_partial_step_recommandation.html.twig
#561    
Modification de l'affichage des boutons suite aux retours concernant l'audit DSFR : les boutons ne doivent pas prendre toute la largeur mais s'ajuster à la taille du texte.
Dans les formulaires, les boutons Suivant / Précédent ne doivent pas être des liens.
> [DSFR] Modification de l'affichage des boutons

- templates/front/index.html.twig
- templates/security/login.html.twig
#576   
Selon le DSFR
- si un lien est au milieu du texte, il doit être gris comme le texte
- si un lien est esseulé, il doit être bleu
* Sur la page d'accueil, le lien "En savoir plus" devient bleu
* Sur la page connexion, le lien "Mot de passe oublié" devient bleu
> [DSFR] Couleur bleue pour 2 liens

- .env
- .env.sample
- config/packages/framework.yaml
- config/packages/security.yaml
- config/packages/twig.yaml
- config/services.yaml
- templates/common/analytics.html.twig
#1953    
Ajout du flag Secure sur tous les cookie utilisé sur la plateforme
Le comportement reste le même en local
* Ajout du flag pour les cookies déposé par Matomo
* Ajout du flag pour les cookies déposé par Symfony 
L'environnement local reste en http et le comportement en environnement local reste le même. 
Test à effectuer sur la review app qui est en [https://stop-punaises-staging-pr573.osc-fr1.scalingo.io/)](https://stop-punaises-staging-pr573.osc-fr1.scalingo.io/) 
Nouvelle variable d'environnement (doit rester à l'identique en dev)
```
MATOMO_ENABLE=0
MATOMO_SITE_ID=
```
Mise à jour des variables d'environnements effectuées sur les différents applications (prod, staging)
https://matomo.org/faq/general/faq_25936/
> [Sécurité] Sécurisation des cookies

- assets/controllers/form_signalement_erp_transport.js
- templates/front/contact.html.twig
- templates/front/index.html.twig
- templates/front/information.html.twig
- templates/front/politique-de-confidentialite.html.twig
- templates/security/reset_password_link_sent.html.twig
#587
#590 
L'auditeur accessibilité 
- déconseille d'utiliser des doubles balises de sauts de ligne pour l'affichage, mais plutôt diviser en plusieurs paragraphes quand nécessaire.
- conseille d'utiliser un titre de deuxième niveau sur la première zone de la page Contact
> [Accessibilité] Remplacement des doubles balises br, amélioration structure titres page Contact

- assets/styles/app.scss
#584    
Bug dans le DSFR : lors de la navigation clavier, il n'y a pas de focus sur le logo Punaises.
J'ai rajouté une règle css pour le gérer.
> [Accessibilité - Logo header] Ajout d'un focus lors de la navigation au clavier

- assets/styles/app.scss
- templates/common/header-back.html.twig
- templates/common/header.html.twig
#583   
Actuellement :
- sur desktop, la page en cours n'est pas mise en avant
- sur mobile, la page en cours est colorée en rouge
L'auditeur propose d'utiliser le composant de [Navigation principale](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/navigation-principale/).
Mais nous utilisons le composant [Entête](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/en-tete) qui me semble plus approprié. Je reviendrai vers lui à ce sujet.
J'ai donc apporté une micro-modification css pour
- souligner la page en cours sur desktop
- mettre une bordure à gauche sur mobile
> [Accessibilité - Menu] Modification de l'affichage de la page en cours

- assets/styles/app.scss
- templates/common/footer.html.twig
- templates/common/header-back.html.twig
- templates/common/header.html.twig
- templates/front/contact.html.twig
- templates/front/index.html.twig
- templates/front/information.html.twig
#586
#591
#599
Amélioration des liens sur les pages Accueil, Information et Contact
> [Accessibilité] Amélioration des liens sur les pages Accueil, Information et Contact

- assets/styles/app.scss
- templates/base-back.html.twig
- templates/base.html.twig
- templates/common/footer.html.twig
- templates/front/mentions-legales.html.twig
#588 
#594
Prise de focus sur les liens d'échappement
- Ajout d'une balise `<main>` avec un attribut `tagindex`
- Ajout d'un `tagindex` sur le `<footer>`
Prise en compte du tableau de la page Mentions légales : éviter qu'il ne déclenche un scroll horizontal pour l'ensemble de la page.
Toujours sur la page Mentions Légales : L'auditeur signale que le lien `exercer-son-droit-dacces` dépasse de l'écran en responsive et préconise des règles css. Je n'ai pas réussi à reproduire, mais j'ai tout de même appliqué la règle css sur son paragraphe.
> [Accessibilité] Amélioration liens d'echappement sur toutes les pages, et responsive sur Mentions légales

- src/Form/ContactType.php
- templates/front/contact.html.twig
#589 
#592 
#593   
Amélioration de la gestion des erreurs du formulaire de contact
* Modification de l'affichage des champs pour pouvoir utiliser les messages d'erreur DSFR
* Ajout du format attendu sous les champs
* Ajout de l'attribut autocomplete sur les champs nom et email pour que ce soit automatiquement proposé
> [Accessibilité - Contact] Meilleure gestion des erreurs

- templates/dashboard/index.html.twig
#629    
Utilisation correcte des cartes dsfr pour le tableau de bord : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/carte/
* Déplacement des badges dans une div `<div class="fr-card__header">`
>  [Accessibilité - Audit] [Tableau de bord - 10.3] Page compréhensible sans css

- templates/front_signalement/_partial_step_autotraitement_info.html.twig
- templates/front_signalement/_partial_step_autotraitement_sent.html.twig
- templates/front_signalement/_partial_step_info_intro.html.twig
- templates/front_signalement/_partial_step_info_locataire.html.twig
- templates/front_signalement/_partial_step_info_logement.html.twig
- templates/front_signalement/_partial_step_info_problemes.html.twig
- templates/front_signalement/_partial_step_info_usager.html.twig
- templates/front_signalement/_partial_step_insectes_larves_intro.html.twig
- templates/front_signalement/_partial_step_insectes_larves_oeufs.html.twig
- templates/front_signalement/_partial_step_insectes_punaises.html.twig
- templates/front_signalement/_partial_step_professionnel_info.html.twig
- templates/front_signalement/_partial_step_professionnel_sent.html.twig
- templates/front_signalement/_partial_step_recommandation.html.twig
- templates/front_signalement/_partial_step_resume.html.twig
- templates/front_signalement/_partial_step_traces_punaises_dejections.html.twig
- templates/front_signalement/_partial_step_traces_punaises_intro.html.twig
- templates/front_signalement/_partial_step_traces_punaises_piqures.html.twig
- templates/signalement_create/index.html.twig
#617 
Remplacer à chaque étape du formulaire, page intermédiaire et de confirmation le titre h2 par à h1
* Remplacement de balise mais conservation du style via les classes DSFR appropriées
- Etape du formulaire
- Page intermédiaire
- Page de confirmation Pro
- Page de confirmation Auto traitement
- Page de confirmation locataire
> [Accessibilité - Audit] [Formulaire signalement - 9.1] Utilisation des titres

- templates/entreprise_list/index.html.twig
- templates/entreprise_view/index.html.twig
- templates/signalement_list/erp-transports.html.twig
- templates/signalement_list/historique.html.twig
- templates/signalement_list/hors-perimetre.html.twig
- templates/signalement_list/signalements.html.twig
#631 #633
Ajout de titres sur les tableaux n'ayant pas via l'attribut` aria-labelledby`
Ajout de l'attribut `role="status"` sur les titre de tableau de type "x éléments trouvés"
> [Accessibilité - Audit] [Liste signalements - 5.4] Titre associé au tableau

- templates/base-back.html.twig
- templates/base.html.twig
#630    
Ajout d'une meta dans le BO pour adapter l'affichage à la largeur de l'écran en responsive
* ajout de la meta
> [Accessibilité - Audit] [Pages du BO - 10.11] Affichage sans scroll en responsive

- templates/common/components/progression-signalement.html.twig
#109 
#642
#649   
Utiliser complètement l'indicateur d'étapes dans le suivi usager : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/indicateur-d-etapes/
* Mise à jour du twig de progression du suivi usager
> [Accessibilité - Audit] [Suivi usager - 3.1] Indicateur d'étape

- templates/bundles/TwigBundle/Exception/error.html.twig
- templates/bundles/TwigBundle/Exception/error403.html.twig
- templates/bundles/TwigBundle/Exception/error404.html.twig
- templates/front/contact.html.twig
- templates/front/politique-de-confidentialite.html.twig
- templates/security/login.html.twig
- templates/security/reset_password.html.twig
- templates/security/reset_password_link_sent.html.twig
- templates/security/reset_password_new.html.twig
- templates/sitemap/index.html.twig
#640    
Suite aux retours de l'auditeur, des balises `div` ont été changées en balise `main` dans les fichier `base` et `base_back`.
Quand j'ai fait ça, j'ai pas pensé qu'il y en avait déjà sur certaines pages.
C'était le cas sur 
- les pages d'erreur
- la page contact
- politique de confidentialité
- login
- mot de passe oublié
- plan du site
> [Accessibilité - W3C] Suppression de doublons de balises main

- assets/styles/app.scss
- templates/front/information.html.twig
- templates/sitemap/index.html.twig
#595
#596
#597
#598
#601
#610
Corrections sur les descriptions d'image et contrastes sur la page Informations et Plan du site
Attention : une partie des modifications consiste à la rédaction de description précise sur certaines images. Je suis largement ouvert aux retours, j'ai fait comme j'ai pu !
> [Accessibilité - Informations] Corrections sur les descriptions d'image et les contrastes

- templates/base.html.twig
- templates/security/_partial_link_account_activation.html.twig
- templates/security/_partial_link_account_login.html.twig
- templates/security/_partial_link_forgotten_password.html.twig
- templates/security/login.html.twig
- templates/security/reset_password.html.twig
- templates/security/reset_password_new.html.twig
#624 
#625 
#626 
#627 
#628 
Ajustements sur la page de login vis à vis de l'audit d'accessibilité :
- Remplissage automatique des champs avec l'attribut autocomplete
- Modification des boutons de changement de page (activation / mot de passe oublié)
- Liaison de l'erreur d'identification au champ e-mail
- Affichage de statut d'erreur dans le titre de la page
**Attention**
#624, #625 et #627 sont liés
J'ai essayé de tout prendre en compte, mais il se peut que j'ai mal compris une indication.
> [Accessibilité - Login] Ajustements divers

- src/Form/EmployeType.php
- src/Form/EntrepriseType.php
- src/Form/SignalementFrontType.php
- src/Form/SignalementHistoryType.php
- templates/front_signalement/_partial_step_home.html.twig
- templates/front_signalement/_partial_step_info_logement.html.twig
- templates/security/reset_password_new.html.twig
- templates/signalement_create/tab-1.html.twig
#623    
Description de la modification apportée
* Ajout attribut autocomplete contextualisé sur les champs de formulaire
https://developer.mozilla.org/fr/docs/Web/HTML/Attributes/autocomplete
> [Accessibilité - Audit] [Formulaire signalement - 11.13] Faciliter remplissage automatique

- assets/styles/app.scss
- src/EventSubscriber/SignalementAddedSubscriber.php
- src/Manager/EventManager.php
- templates/common/components/signalement-detail-evenements.html.twig
- templates/front_suivi_usager/index.html.twig
- templates/front_suivi_usager/modal-close-signalement.html.twig
- templates/front_suivi_usager/modal-empty-estimations.html.twig
- templates/front_suivi_usager/modal-probleme-resolu-pro.html.twig
- templates/front_suivi_usager/modal-probleme-resolu.html.twig
- templates/front_suivi_usager/modal-toujours-punaises-pro.html.twig
- templates/front_suivi_usager/modal-toujours-punaises.html.twig
#644   
#648
#651
#645
Modifications sur la page de suivi usager
* Modification sur la couleur de date des évenemtns
* Dans la modale de confirmation d'arrêt de procédure utilisation d'une liste structurée `<ul>`
* Dans différentes modales  (dont arrêt de la procédure) transformation du lien "< Retour" etn bouton Retour
* Transformation du lien Télécharger le protocole, dans la page de suivi et dans la liste d'événement (si autotraitement) pour utiliser le DSFR https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/telechargement-de-fichier
> [Suivi usager] Couleurs, structuration modale et lien téléchargement

- templates/signalement_view/tab-intervention.html.twig
#673    
Modification du champ d'upload dans la fiche signalement (label, conseil, type de fichiers)
> [Accessibilité - BO - Fiche signalement] Modification du champ d'upload

- templates/signalement_create/tab-2.html.twig
#660
Dépôt signalement BO: Modification de l'ordre dans le HTML du bouton Valider et précédent pour la cohérence de la navigation par tabulations
> [Accessibilité - Audit] [BO Ajout signalement - 12.8] Ordre de tabulation incohérent

- assets/styles/app.scss
#669    
Modification de la couleur de niveau d'infestation faible pour améliorer le contraste
> [Accessibilité - Niveau infestation] Modification de la couleur faible pour un meilleur contraste

- assets/styles/app.scss
- templates/front_signalement/_partial_step_resume.html.twig
#619   
Sur l'étape de résumé, avec un nom/prénom/email long, le texte sortait de la zone et provoquait l'apparition d'un scroll horizontal en format mobile.
Ajout d'une règle css pour que ça revienne à la ligne automatiquement sur cette zone, si nécessaire.
> [Accessibilité - Formulaire signalement] Amélioration responsive sur l'étape de résumé

- src/Form/SignalementFrontType.php
- templates/front_signalement/_partial_step_traces_punaises_piqures.html.twig
#620
Tous les label des radio buttons sont géré par le `components/form/list-radio-buttons.html.twig`
> [Accessibilité - Audit] [Formulaire signalement - 11.7] Légende mal reliée à des radio

- assets/controllers/list_employes.js
- assets/controllers/list_entreprises.js
- assets/controllers/list_signalement.js
- assets/styles/app.scss
- src/Service/Signalement/SignalementOccupantDataTableHandler.php
- templates/common/components/signalement-detail.html.twig
- templates/entreprise_list/index.html.twig
- templates/entreprise_view/index.html.twig
- templates/front/accessibilite.html.twig
- templates/front/entreprises-labelisees.html.twig
- templates/front/index.html.twig
- templates/front/mentions-legales.html.twig
- templates/front/politique-de-confidentialite.html.twig
- templates/signalement_list/erp-transports.html.twig
- templates/signalement_list/historique.html.twig
- templates/signalement_list/hors-perimetre.html.twig
- templates/signalement_list/modal-signalement-erp-transports.html.twig
- templates/signalement_list/signalements.html.twig
- templates/signalement_view/tab-intervention.html.twig
- templates/signalement_view/tab-logement.html.twig
#672
#685   
Différentes modifications pour utiliser la plateforme sans feuille de style 
- ajout de `nouvelle fenêtre` dans l'attribut `title` de différents liens sur le site
- les boutons de visualisation et suppression de photos sur la fiche signalement sont accessibles sans feuille de style
- dans les listes de signalements / entreprises / employés, les boutons d'accès sont accessibles sans feuille de style
- sur ces mêmes listes, une liste déroulante permet de trier les tableaux par colonne, dans le sens ASC
> [Accessibilité - Plusieurs pages] Utilisation sans feuille de style

- src/Controller/SignalementViewController.php
- src/Form/SignalementHistoryType.php
#688
#689
Sentry remonte des bugs sur des montants saisis en tant qu'entier ou non.
Une partie sera corrigée par des retours accessibilité, je me suis contenté d'ajuster la partie back dans l'immédiat.
Lorsqu'une entreprise fait une estimation avec un nombre avec décimale, automatiquement, ça arrondissait à l'inférieur.
Lorsqu'une entreprise crée un signalement historique avec un texte à la place du prix, ça plante.
* Pour l'estimation, arrondi au supérieur
* Pour le texte à la place du prix, changement de type de champ dans le FormType
> [QA - Sentry] Corrections liées aux montants entiers ou non

- .env
- .env.sample
- config/packages/framework.yaml
- public/index.php
#639    
Augmentation de la durée de session par défaut (celle du PHP)
N'est pas défini dans le buildpack PHP de scalingo https://github.com/Scalingo/php-buildpack/blob/master/conf/php/php.ini  elle prend donc la valeur par défaut de PHP (1440s = 24 minutes)
[session.cookie_lifetime](https://www.php.net/manual/fr/session.configuration.php#ini.session.cookie-lifetime:~:text=session.cookie_lifetime%20int,et%20session_set_cookie_params().) (0 par défaut)
> Spécifie la durée de vie du cookie en secondes. La valeur de 0 signifie : "Jusqu'à ce que le navigateur soit éteint". La valeur par défaut est 0. Voir aussi [session_get_cookie_params()](https://www.php.net/manual/fr/function.session-get-cookie-params.php) et [session_set_cookie_params()](https://www.php.net/manual/fr/function.session-set-c …
> [Accessibilité - Audit] [Toutes les pages - 13.1] Augmenter la limite de temps avant la fin de la session d'au moins 20 heures

- templates/common/components/signalement-detail-evenements.html.twig
- templates/front_suivi_usager/index.html.twig
- templates/signalement_create/index.html.twig
- templates/signalement_create/tab-1.html.twig
- templates/signalement_create/tab-2.html.twig
- tests/Functional/Controller/Front/SuiviUsagerViewControllerTest.php
#655 
#647    
Mise à jour de la hiérarchie des titres sur le suivi usager, la fiche signalement dans le BO, et l'ajout de signalement dans le BO
* Mise à jour des twigs
> Hiérarchie des titres

- assets/controllers/list_employes.js
- assets/controllers/list_entreprises.js
- assets/controllers/list_signalement.js
- assets/styles/app.scss
#632
#670   
Amélioration des liens dans le BO
- les liens de pagination de listes
- les liens dans la fiche de suivi d'un signalement
L'auditeur conseillait d'utiliser la pagination du DSFR, mais la structure est très différente de celle de Datatable.
J'ai donc opté plutôt pour l'édition en js des title et roles des balises pour faire correspondre.
> [Accessibilité - BO] Amélioration des liens

- assets/controllers/list_employes.js
- assets/controllers/list_entreprises.js
- assets/controllers/list_signalement.js
- assets/styles/app.scss
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Service/Signalement/SignalementOccupantDataTableHandler.php
- src/Twig/AppExtension.php
- templates/entreprise_list/index.html.twig
- templates/entreprise_view/index.html.twig
- templates/signalement_list/erp-transports.html.twig
- templates/signalement_list/historique.html.twig
- templates/signalement_list/hors-perimetre.html.twig
- templates/signalement_list/signalements.html.twig
#701   
- Correction sur l'affichage et l'accord des différents titres
- Correction de l'affichage pour les niveaux d'infestation vides
- Correction de textes de DataTables qui étaient restés en anglais
> [BO - Listes] Corrections d'accessibilité sur les titres et textes

- assets/controllers/list_employes.js
- assets/controllers/list_entreprises.js
- assets/controllers/list_signalement.js
- assets/styles/app.scss
- templates/entreprise_list/index.html.twig
- templates/entreprise_view/index.html.twig
- templates/signalement_list/erp-transports.html.twig
- templates/signalement_list/historique.html.twig
- templates/signalement_list/hors-perimetre.html.twig
- templates/signalement_list/signalements.html.twig
#710   
Suite à l'audit accessibilité, il est conseillé de supprimer les boutons de tri de DataTable.
On intègre aussi le style fr-table au tableau.
Et on masque les infos des signalements historiques qui apparaissent quand on affiche la page sans style.
> [BO - Signalement] Suppression boutons de tri

- assets/controllers/component_file_auto_submit.js
- assets/controllers/form_signalement_erp_transport.js
- assets/controllers/form_signalement_front.js
- assets/styles/app.scss
- src/Form/SignalementFrontType.php
- templates/front_signalement/_partial_step_autotraitement_info.html.twig
- templates/front_signalement/_partial_step_professionnel_info.html.twig
#703    
Dans l'affichage d'un signalement dans le BO :
- avec une longue adresse e-mail (par exemple), on avait un scroll horizontal
- lors de l'envoi de photo, le messsage d'erreur n'était pas assez précis
> [BO - Signalement] Affichage responsive et message d'erreur d'upload

- templates/front/information.html.twig
#716    
On sort la transcription de la balise `<figure>`, car la balise `<figcaption>` doit être premier ou dernier enfant (Erreur qu'on avait reprise depuis le composant DSFR)
Autre souci que je ne sais pas comment reproduire : certaines synthèses vocales (je ne sais pas comment activer) sortent de la modale quand elle est ouverte. 
J'ai regardé les différences avec le composant modal du DSFR.
Le contenu est dans un paragraphe `<p>`, je l'ai remis, au cas où.
Il y a un `role="dialog"`, mais celui-ci est déconseillé par le w3c parce qu'il fait doublon avec la balise `<dialog>`
Donc je ne sais pas comment corriger...
> [Accessibilité] Corrections d'affichage des infographies

- src/Entity/Enum/InfestationLevel.php
- src/Service/Signalement/SignalementOccupantDataTableHandler.php
- templates/common/components/niveau-infestation.html.twig
#718   
La lecture des niveaux d'infestation pouvait se faire directement avec les champs suivants ce qui ne facilitait pas la compréhension. On ajoute donc des informations via les attributs.
> [Accessibilité] Ajout d'indication sur les niveaux d'infestation pour faciliter la lecture par synthèse vocale

- assets/app.js
- assets/controllers/reinit_password.js
- config/packages/translation.yaml
- migrations/Version20240319132426.php
- src/Controller/Security/AccountActivationController.php
- src/Controller/Security/ResetPasswordController.php
- src/Entity/User.php
- src/Service/Mailer/MailerProvider.php
- src/Service/Token/ActivationToken.php
- templates/security/login.html.twig
- templates/security/reset_password_link_sent.html.twig
- templates/security/reset_password_new.html.twig
- tests/Functional/Controller/Security/AccountActivationControllerTest.php
- tests/Unit/Entity/UserTest.php
#551
Ajout de contraintes de validation pour des mot de passe plus fort : 
- 8 caractères minimum
- 1 caractère majuscule minimum
- 1 caractère minuscule minimum
- 1 chiffre minimum
- 1 caractère spécial minimum
- Passage de l'app en français par défaut
- Route unique `activate_account` pour activer son compte / modifier sont mot de passe
- Ajout de l'option "Afficher" sur les champs mot de passe de la page création/modification de mot de passe
- Affichage du message flash de succès aprés redirection sur la page login
- Ajout de tests
`make execute-migration name=Version20240319132426 direction=up`
`make npm-build`
> Fixer des contraintes de longueur et de complexité des mots de passe

- .env
- .env.sample
#726   
Ajout du "unsafe-eval" dans la CSP pour Matomo. (cf description dans le ticket)
:warning: n'ayant pas le souci en local, je ne sais pas commemnt le tester, je ne suis même pas sûre que ce soit le vrai pb... c'est juste de la déduction.
* Changement des .env
>   [Matomo] Très peu de tracking depuis la mise en ligne du 16 février

- templates/common/footer.html.twig
- templates/front/accessibilite.html.twig
- templates/sitemap/index.html.twig
#494    
Sur la base des éléments de https://ara.numerique.gouv.fr/rapports/sCeFoDWFkfkhCJxlnM7Jw/declaration-daccessibilite, il est nécéssaire de compléter la déclaration d'accessibilité. 
Regard sur ce qui a été fait sur dossier facile qui est partiellement conforme également 
* https://www.dossierfacile.logement.gouv.fr/accessibilite
* Ajout des sections manquantes dans la déclaration d'accessibilité
> [Accessibilité] Afficher le niveau d'accessibilité sur toutes les pages après l'audit

- .env.sample
- .github/workflows/main.yml
- README.md
- config/packages/doctrine.yaml
- docker-compose.yml
#742   
Scalingo nous propose de passer rapidement à MySQL 8, puisqu'ils vont arrêter la maintenance de MySQL 5.7 et migreront à partir du 1er juillet.
Par ailleurs, on pourra en profiter pour utiliser des fonctionnalités plus avancées à présent.
Afin de passer en MySQL 8, il y avait 2 vérifications à faire sur les tables (cf ici : https://doc.scalingo.com/databases/mysql/mysql-8-prerequisites) :
- Toutes les tables utilisent le moteur InnoDB
- Toutes les tables ont des clés primaires
C'est bien le cas.
J'ai fait pas mal de tests, le passage à la version 8 semble indolore.
Lors du passage sur develop (lors du merge), il faudra 
- faire une sauvegarde de la base
- passer MySQL en version 8 via le dashboard Scalingo sur l'app de staging
- faire des tests sur staging
* Modification de la …
> [INFRA] Migration de MySQL 5.7 vers 8.0

- .env
- .env.sample
- templates/base-back.html.twig
#750    
Changement de cdn pour la librairie js leaflet car unpkg n'est plus fiable
* Changement de cdn
* Ajout du nouveau cdn dans la security csp header
[edit] Modifier `SECURITY_CSP_HEADER_VALUE` dans `.env.local`
>  [QA] Passer de unpkg a jsdelivr 

- src/Controller/Front/SuiviUsagerViewController.php
- templates/front_suivi_usager/modal-choice-estimation.html.twig
#747
Sécurisation de la route `app_signalement_estimation_choice` afin qu'une réponse acceptation/refus ne puisse être envoyé qu'une seule fois et pour un signalement dont le lien m'as été transmis
> [Sécurité] Ajout de controles sur la route "app_signalement_estimation_choice

- src/Service/Import/Signalement/SignalementImportLoader.php
#754    
Lorsqu'on a ajouté le principe de type de signalement, on ne l'a pas répercuté dans la procédure d'import CSV.
- Exemple : `make console app="import-signalement 655cb685dbe6a"`
> [Import CSV] Ajout du type de signalement

- scripts/upload-s3.sh
- src/Command/ImportSignalementCommand.php
- src/Service/Import/Signalement/SignalementImportLoader.php
- src/Service/Import/Signalement/SignalementImportMapper.php
#756   
On ne pouvait importer les signalements qu'entreprise par entreprise. Mais on a plus de 100 fichiers à importer d'un coup.
On rend facultatif l'option de l'uuid de l'entreprise pour ajouter une colonne dans le fichier.
* Il existe à présent une colonne possible dans les fichiers d'import dont le nom est `Entreprise` et qui prend l'uuid d'une entreprise.
* Modification de la commande d'upload
* `./scripts/upload-s3.sh signalement [uuid_entreprise]` existe toujours, mais on peut aussi appeler `./scripts/upload-s3.sh signalements-multi`
* Modification de la commande d'import
* `make console app="import-signalement [uuid_entreprise]"` existe toujours, mais on peut aussi appeler `make console app="import-signalement"`
J'ai uploadé un fichier qui fonctionne avec les fixtures et qui …
> [Import] Possibilité d'importer des signalements pour plusieurs entreprises

- config/services.yaml
- migrations/Version20240923083351.php
- src/Dto/Command/CommandContext.php
- src/Entity/Behaviour/EntityHistoryInterface.php
- src/Entity/Enum/HistoryEntryEvent.php
- src/Entity/HistoryEntry.php
- src/Entity/User.php
- src/EventListener/AuthentificationHistoryListener.php
- src/Factory/HistoryEntryFactory.php
- src/Manager/HistoryEntryManager.php
- src/Repository/HistoryEntryRepository.php
- tests/Functional/Manager/HistoryEntryManagerTest.php
#791 
#792 
Historisation de l'ensemble des accès à la plateforme, tout en ayant mis en place les colonnes `source` et `changes` 
* `source` : origine de la modification (une url ou une commande)
* `changes` : changement qui ont été apportés sur la ressource notamment lors de la modification
* Création d'une table HistoryEntry qui stocke l'ensemble des logins au SI
* A terme, elle permettra de stocker l'ensemble des événements de modification du site
* Ajout de l'interface `EntityHistoryInterface` utilisée pour s'assurer qu'une entité supporte l'historisation.
`make execute-migration name=Version20240923083351 direction=up`
> [Historique] Initier un système d'historisation des actions BO, et historisation des logins

- .env
- .env.sample
- assets/app.js
- assets/controllers/form_helper.js
- assets/controllers/form_signalement_erp_transport.js
- assets/controllers/form_signalement_front.js
- assets/styles/app.scss
- config/app/csp.yaml
- config/services.yaml
- public/index.php
- src/EventListener/ContentSecurityPolicyListener.php
- templates/cartographie/curseur.html.twig
- templates/common/analytics.html.twig
- templates/common/components/macro-forms.html.twig
- templates/front/signalement-type-list.html.twig
#772    
Tentative d'avoir une CSP plus stricte
* Génération d'une CSP via un listener src/EventListener/ContentSecurityPolicyListener.php et ajout de nonces à la volée, les différents paramètres étant définis dans config/app/csp.yaml (et ils sont plus stricts)
* Externalisation de tous les scripts inline pouvant l'être
* Externalisation de tous les styles inline pouvant l'être
* Utilisation de nonces sur tous les styles et les scripts ne pouvant être externalisés (certains pourraient l'être en fait)
* Utilisation de <image à la place de <use dans les svg
Supprimer les variables SECURITY_CSP_HEADER_VALUE des fichiers d'environnement
:warning: Les tests sont à faire console ouverte pour voir les erreurs en plus de l'aspect fonctionnel.
> [Technique] Améliorer la CSP

- .scalingo/nginx/server.location
- public/js/maps.js
#773    
J'ai fait le tour des scans initiés sur mozilla observatory https://observatory.mozilla.org/analyze/stop-punaises.gouv.fr
Il y a beaucoup moins de choses que sur Histologe, donc pas grand-chose à faire.
http://dashlord.mte.incubateur.net/url/stop-punaises-beta-gouv-fr/securite/
On a 5 points de moins sur on va sur stop-punaises.beta.gouv.fr à cause de la redirection vers stop-punaises.gouv.fr.
Donc je me suis contentée d'ajouter les mêmes headers de sécurité qu'on avait ajouté sur histologe (la CSP ayant été renforcée dans un autre ticket)
* Modification des entêtes
`make down && make run`
```bash
curl -I http://localhost:8090
````
> [Technique] Vérifier (et corriger) les vulnérabilités détectées par Nuclei 

- .buildpacks
- .docker/php-fpm/Dockerfile
- .env
- .env.sample
- .slugignore
- Makefile
- composer.json
- composer.lock
- config/bundles.php
- config/packages/clamav.yaml
- docker-compose.yml
- package-lock.json
- scalingo.json
- src/Entity/Signalement.php
- src/Exception/File/MalwareDetectedException.php
- src/Security/FileScanner.php
- src/Service/Upload/UploadHandlerService.php
- templates/front_signalement_erp/index.html.twig
cf : https://github.com/MTES-MCT/histologe/pull/2839
#782    
Ajout d'un scan antivirus (via clamav) sur les fichiers uploadé sur le formulaire de dépot du signalement,la page de suivi usager du signalement et la page BO du signalement
* Ajout du buildpack clamav pour scalingo
* Ajout d'un conteneur docker pour le fonctionnement de clamav en local
* Ajout de l'extension php sockets pour la communication avec clamav
* Ajout du bundle sineflow/clamav pour l'utilisation sous Symfony
```
-----------------------------67889249634044727342552075142
Content-Disposition: form-data; name="file-upload[]"; filename="bonjour.txt"
Content-Type: text/plain
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
-----------------------------67889249634044727342552075142
```
> [Socle sécurité] Anti-malware sur le flux de fichiers

- templates/base-back.html.twig
#807
Suppression du DSFR.js de la page map duquel on a pas besoin et qui provoque un conflit avec leaflet
`make npm-build`
> [Cartographier] Bug d'affichage

- src/Controller/SignalementListController.php
- src/Controller/SignalementMessageController.php
- src/Controller/SignalementResolveController.php
- src/Controller/SignalementViewController.php
- src/Security/Voter/InterventionVoter.php
- src/Security/Voter/SignalementVoter.php
- templates/signalement_view/signalement.html.twig
- templates/signalement_view/tab-signalement.html.twig
#797    
Ajout de sécurités sur les controllers pour l'utilisation de certaines fonctionnalités
> [Sécurité] Cloisonnement des rôles
